### ISSUE TITLE
Automating Git configuration with ./deploy_prod.sh

### ISSUE THREAD

**Issue by benuklove** [makaimc/fsp-deployment-guide#16]
Task: ensure deploy key is on remote server.

This is failing and I'm not sure why.  I have added deploy_key.pub to the Deploy Keys section on my forked repo of your cyoa repo and followed all other steps too.  Do I also need a deploy_key private file on my local machine?

![screenshot from 2017-08-13 22-37-31](https://user-images.githubusercontent.com/11739177/29258026-070fab4e-807c-11e7-9c40-d6d4e13b6667.png)

**Comment by mattmakai** [comment]
hey @benuklove, from your screenshot the `~` references your home directory. looks like it's in the middle of a path, which won't work. double check the path where the key file is supposed to be located, the playbook is failing because the key does not exist at that path (which is probably erroring out because that is not a valid path)

**Comment by benuklove** [comment]
Thanks!
